// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcauXRm2ejxtbezL_lGHDzZowFyjA-6Sw',
    appId: '1:649571274738:web:fb9222c76fe776c290e56b',
    messagingSenderId: '649571274738',
    projectId: 'planningku-app',
    authDomain: 'planningku-app.firebaseapp.com',
    storageBucket: 'planningku-app.appspot.com',
    measurementId: 'G-2PWPT3KXEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-3eyYCHvGWh87rUyaYfwQAEgfhzQlqM',
    appId: '1:649571274738:android:09be0354fbb037a190e56b',
    messagingSenderId: '649571274738',
    projectId: 'planningku-app',
    storageBucket: 'planningku-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRMMwGaDVjgB44U34-S7NLLwJGxDI32k4',
    appId: '1:649571274738:ios:c71c93f2c418ba3e90e56b',
    messagingSenderId: '649571274738',
    projectId: 'planningku-app',
    storageBucket: 'planningku-app.appspot.com',
    iosClientId: '649571274738-qodc5eedmbd12psbnu4tgqslt5g56c3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRMMwGaDVjgB44U34-S7NLLwJGxDI32k4',
    appId: '1:649571274738:ios:c71c93f2c418ba3e90e56b',
    messagingSenderId: '649571274738',
    projectId: 'planningku-app',
    storageBucket: 'planningku-app.appspot.com',
    iosClientId: '649571274738-qodc5eedmbd12psbnu4tgqslt5g56c3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicoding',
  );
}
