// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk9I2olC9I0nD_jxOLWROSzxCqXPG8PjE',
    appId: '1:392485463518:web:dbc3494bba401485b3694f',
    messagingSenderId: '392485463518',
    projectId: 'agenda-app-1aeb9',
    authDomain: 'agenda-app-1aeb9.firebaseapp.com',
    storageBucket: 'agenda-app-1aeb9.appspot.com',
    measurementId: 'G-69TTE5RJJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOE2FOhcUtFisWxhwx4nREeq5YjN0TqvA',
    appId: '1:392485463518:android:ce8059e98027f065b3694f',
    messagingSenderId: '392485463518',
    projectId: 'agenda-app-1aeb9',
    storageBucket: 'agenda-app-1aeb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqyTZehiEVrTeaTKqBl68m40MIGRZh04',
    appId: '1:392485463518:ios:695faca8a95cf435b3694f',
    messagingSenderId: '392485463518',
    projectId: 'agenda-app-1aeb9',
    storageBucket: 'agenda-app-1aeb9.appspot.com',
    iosClientId: '392485463518-iba2tse257b6vl6ggci16tm497s882ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicoding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSqyTZehiEVrTeaTKqBl68m40MIGRZh04',
    appId: '1:392485463518:ios:695faca8a95cf435b3694f',
    messagingSenderId: '392485463518',
    projectId: 'agenda-app-1aeb9',
    storageBucket: 'agenda-app-1aeb9.appspot.com',
    iosClientId: '392485463518-iba2tse257b6vl6ggci16tm497s882ri.apps.googleusercontent.com',
    iosBundleId: 'com.example.dicoding',
  );
}
